### ISSUE TITLE
Cannot run dune3D on nvida graphics and wayland

### ISSUE THREAD

**Issue by yodatak** [flathub/org.dune3d.dune3d#16]
flatpak run org.dune3d.dune3d
realize
dune3d: ../src/dispatch_common.c :872 : epoxy_get_proc_address:  l'assertion « 0 && "Couldn't find current GLX or EGL context.\n" » a échoué.

nvidia-smi
Fri Dec  6 00:20:31 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:09:00.0  On |                  N/A |
| 37%   34C    P5             30W /  170W |    1020MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |

# System Details Report
---

## Report details
- **Date generated:**                              2024-12-06 00:23:13

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. PRIME B450M-K
- **Memory:**                                      48.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 2600 × 12
- **Graphics:**                                    NVIDIA GeForce RTX™ 3060
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            2409
- **OS Name:**                                     Bazzite 41 (FROM Fedora Silverblue)
- **OS Build:**                                    Stable (F41.20241125)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.9-303.bazzite.fc41.x86_64

**Comment by carrotIndustries** [comment]
Please open this issue in the Dune 3D repo: https://github.com/dune3d/dune3d
